export type StatusColor = "green" | "light-green" | "yellow" | "red";

export type Department = "Finance" | "Content" | "Marketing" | "Sales" | "Product";

export interface WeekData {
  actual: number | string;
  projection: number | string;
}

export interface WeekConfig {
  label: string;
  dateLabel: string; // dd/mm format
  start: string; // ISO date string (start of week, NZ time)
  end: string;   // ISO date string (end of week, NZ time)
}

export interface Metric {
  name: string;
  department: Department;
  catchUp: { actual: number | string; projection: number | string };
  weeks: WeekData[];
  monthlyActual: number | string;
  monthlyTarget: number | string;
  status: StatusColor;
  owner: string;
  source: string;
  description: string;
}

// April 2026 weeks (Monday–Sunday), NZ timezone (Pacific/Auckland)
// DST change: NZDT (UTC+13) → NZST (UTC+12) on Apr 5 at 3am local
// So: Apr 1-4 midnight NZT = T11:00Z (NZDT), Apr 6+ midnight NZT = T12:00Z (NZST)
export const weekConfigs: WeekConfig[] = [
  { label: "W1", dateLabel: "06/04", start: "2026-04-05T12:00:00Z", end: "2026-04-12T12:00:00Z" },
  { label: "W2", dateLabel: "13/04", start: "2026-04-12T12:00:00Z", end: "2026-04-19T12:00:00Z" },
  { label: "W3", dateLabel: "20/04", start: "2026-04-19T12:00:00Z", end: "2026-04-26T12:00:00Z" },
  { label: "W4", dateLabel: "27/04", start: "2026-04-26T12:00:00Z", end: "2026-04-30T12:00:00Z" },
];

export const scorecardMonth = "April 2026";

/** Returns 0-3 for the current active week, 4 if past all weeks, -1 if before month */
export function getCurrentWeekIndex(): number {
  const now = new Date();
  for (let i = 0; i < weekConfigs.length; i++) {
    if (now >= new Date(weekConfigs[i].start) && now < new Date(weekConfigs[i].end)) return i;
  }
  if (now >= new Date(weekConfigs[weekConfigs.length - 1].end)) return weekConfigs.length;
  return -1;
}

/** Returns the index of the most recently completed week (0-3), or -1 if none completed */
export function getCompletedWeekIndex(): number {
  const now = new Date();
  for (let i = weekConfigs.length - 1; i >= 0; i--) {
    if (now >= new Date(weekConfigs[i].end)) return i;
  }
  return -1;
}

export const statusOptions: { value: StatusColor; label: string }[] = [
  { value: "light-green", label: "Ahead" },
  { value: "green", label: "On Track" },
  { value: "yellow", label: "Behind" },
  { value: "red", label: "At Risk" },
];

export const scorecardData: Metric[] = [
  // EVERGREEN METRICS
  {
    name: "Revenue",
    department: "Finance",
    catchUp: { actual: 36672, projection: 474194 },
    weeks: [
      { actual: 136151, projection: 829839 },
      { actual: 173813, projection: 829839 },
      { actual: 193871, projection: 829839 },
      { actual: 136382, projection: 711289 },
    ],
    monthlyActual: 676889,
    monthlyTarget: "$3,675,000",
    status: "red",
    owner: "Lana",
    source: "Daily P&L",
    description: "The total sales generated by the company",
  },
  {
    name: "Cash Collected",
    department: "Finance",
    catchUp: { actual: 34596, projection: 451613 },
    weeks: [
      { actual: 129668, projection: 790323 },
      { actual: 165536, projection: 790323 },
      { actual: 184639, projection: 790323 },
      { actual: 129888, projection: 677418 },
    ],
    monthlyActual: 644327,
    monthlyTarget: "3,500,000",
    status: "red",
    owner: "Lana",
    source: "Stripe + PayPal",
    description: "The actual amount of cash received by the company",
  },
  // CONTENT
  {
    name: "Videos posted last week",
    department: "Content",
    catchUp: { actual: "—", projection: 3 },
    weeks: [
      { actual: "—", projection: 3 },
      { actual: "—", projection: 3 },
      { actual: "—", projection: 3 },
      { actual: "—", projection: 3 },
    ],
    monthlyActual: "—",
    monthlyTarget: 12,
    status: "green",
    owner: "Adam Jahr",
    source: "Notion",
    description: "The total count of videos published on YouTube in the past week",
  },
  {
    name: "Videos in the backlog",
    department: "Content",
    catchUp: { actual: "—", projection: 2 },
    weeks: [
      { actual: "—", projection: 2 },
      { actual: "—", projection: 2 },
      { actual: "—", projection: 2 },
      { actual: "—", projection: 2 },
    ],
    monthlyActual: "—",
    monthlyTarget: "2 per week",
    status: "green",
    owner: "Adam Jahr",
    source: "Notion",
    description: "Videos that have entered production",
  },
  {
    name: "YouTube views",
    department: "Content",
    catchUp: { actual: "109.1k", projection: "250k" },
    weeks: [
      { actual: "217.4k", projection: "250k" },
      { actual: "206.9k", projection: "250k" },
      { actual: "225k", projection: "250k" },
      { actual: "265.3k", projection: "250k" },
    ],
    monthlyActual: "1.02m",
    monthlyTarget: "1m",
    status: "green",
    owner: "Adam Jahr",
    source: "YouTube",
    description: "The total number of videos currently undergoing the editing process",
  },
  {
    name: "New YouTube subscribers",
    department: "Content",
    catchUp: { actual: "1.9k", projection: "1.5k" },
    weeks: [
      { actual: "3.7k", projection: "4k" },
      { actual: "3.8k", projection: "4k" },
      { actual: "3.5k", projection: "4k" },
      { actual: "3.4k", projection: "4k" },
    ],
    monthlyActual: "16.3k",
    monthlyTarget: "16k",
    status: "yellow",
    owner: "Adam Jahr",
    source: "YouTube",
    description: "The total number of new subscribers to the main channel",
  },
  {
    name: "Clicks: YouTube > Skool",
    department: "Content",
    catchUp: { actual: 1129, projection: 2500 },
    weeks: [
      { actual: 4318, projection: 3500 },
      { actual: 3094, projection: 3500 },
      { actual: 3112, projection: 4000 },
      { actual: 2019, projection: 4000 },
    ],
    monthlyActual: 13672,
    monthlyTarget: 15000,
    status: "yellow",
    owner: "Adam Jahr",
    source: "Bitly",
    description: "The number of funnel-clicks on links from YouTube to Skool",
  },
  {
    name: "Clicks: YouTube > Accelerator",
    department: "Content",
    catchUp: { actual: 113, projection: 500 },
    weeks: [
      { actual: 669, projection: 500 },
      { actual: 619, projection: 550 },
      { actual: 608, projection: 600 },
      { actual: 556, projection: 600 },
    ],
    monthlyActual: 2565,
    monthlyTarget: 2250,
    status: "green",
    owner: "Adam Jahr",
    source: "Bitly",
    description: "The number of funnel-clicks on links from YouTube to Accelerator",
  },
  {
    name: "Clicks: Skool > Accelerator",
    department: "Content",
    catchUp: { actual: 0, projection: 0 },
    weeks: [
      { actual: 150, projection: 150 },
      { actual: 138, projection: 200 },
      { actual: 80, projection: 200 },
      { actual: 285, projection: 200 },
    ],
    monthlyActual: 750,
    monthlyTarget: "",
    status: "green",
    owner: "",
    source: "",
    description: "",
  },
  // MARKETING — Email (Kit)
  {
    name: "Emails Sent",
    department: "Marketing",
    catchUp: { actual: "—", projection: "—" },
    weeks: [
      { actual: "—", projection: "—" },
      { actual: "—", projection: "—" },
      { actual: "—", projection: "—" },
      { actual: "—", projection: "—" },
    ],
    monthlyActual: "—",
    monthlyTarget: "—",
    status: "green",
    owner: "Casey",
    source: "Kit",
    description: "Total broadcast emails delivered per week",
  },
  {
    name: "Email Clicks",
    department: "Marketing",
    catchUp: { actual: "—", projection: "—" },
    weeks: [
      { actual: "—", projection: "—" },
      { actual: "—", projection: "—" },
      { actual: "—", projection: "—" },
      { actual: "—", projection: "—" },
    ],
    monthlyActual: "—",
    monthlyTarget: "—",
    status: "green",
    owner: "Casey",
    source: "Kit",
    description: "Total broadcast email clicks per week",
  },
  // MARKETING — Bookings
  {
    name: "Total Bookings",
    department: "Marketing",
    catchUp: { actual: 91, projection: 320 },
    weeks: [
      { actual: 597, projection: 560 },
      { actual: 286, projection: 560 },
      { actual: 205, projection: 560 },
      { actual: 480, projection: 480 },
    ],
    monthlyActual: 1179,
    monthlyTarget: 2480,
    status: "yellow",
    owner: "Casey",
    source: "Booking Sheet",
    description: "",
  },
  {
    name: "Email Bookings",
    department: "Marketing",
    catchUp: { actual: 17, projection: 80 },
    weeks: [
      { actual: 319, projection: 140 },
      { actual: 74, projection: 140 },
      { actual: 34, projection: 140 },
      { actual: 120, projection: 120 },
    ],
    monthlyActual: "",
    monthlyTarget: 620,
    status: "light-green",
    owner: "Casey",
    source: "Booking Sheet",
    description: "",
  },
  {
    name: "Website Views",
    department: "Marketing",
    catchUp: { actual: 891, projection: 2000 },
    weeks: [
      { actual: 2344, projection: 3500 },
      { actual: 2067, projection: 3500 },
      { actual: 1960, projection: 3500 },
      { actual: 3000, projection: 3000 },
    ],
    monthlyActual: "",
    monthlyTarget: 15500,
    status: "red",
    owner: "Casey",
    source: "Booking Sheet",
    description: "",
  },
  {
    name: "Website Booking Rate",
    department: "Marketing",
    catchUp: { actual: "2.61%", projection: "4%" },
    weeks: [
      { actual: "2.79%", projection: "4%" },
      { actual: "2.30%", projection: "4%" },
      { actual: "1.69%", projection: "4%" },
      { actual: "4%", projection: "4%" },
    ],
    monthlyActual: "4.00%",
    monthlyTarget: "",
    status: "red",
    owner: "Casey",
    source: "Booking Sheet",
    description: "The number of bookings made directly through the website",
  },
  {
    name: "Skool Joins",
    department: "Marketing",
    catchUp: { actual: 1294, projection: 1600 },
    weeks: [
      { actual: 3548, projection: 2800 },
      { actual: 2833, projection: 2800 },
      { actual: 2538, projection: 2800 },
      { actual: 2400, projection: 2400 },
    ],
    monthlyActual: "",
    monthlyTarget: 12400,
    status: "green",
    owner: "Casey",
    source: "Booking Sheet",
    description: "The number of bookings made through out Skool Classroom",
  },
  {
    name: "Skool Booking Rate",
    department: "Marketing",
    catchUp: { actual: "3.00%", projection: "4%" },
    weeks: [
      { actual: "4.10%", projection: "4%" },
      { actual: "4.80%", projection: "4%" },
      { actual: "3.20%", projection: "4%" },
      { actual: "4%", projection: "4%" },
    ],
    monthlyActual: "4.00%",
    monthlyTarget: "",
    status: "green",
    owner: "Casey",
    source: "Booking Sheet",
    description: "The number of bookings made through out Skool setter",
  },
  // SALES
  {
    name: "Triage Calls Booked",
    department: "Sales",
    catchUp: { actual: 181, projection: 190 },
    weeks: [
      { actual: 382, projection: 475 },
      { actual: 87, projection: 475 },
      { actual: 475, projection: 475 },
      { actual: 475, projection: 475 },
    ],
    monthlyActual: "",
    monthlyTarget: 2090,
    status: "yellow",
    owner: "AJ",
    source: "Booking Sheet",
    description: "",
  },
  {
    name: "Triage Show Rate",
    department: "Sales",
    catchUp: { actual: 57, projection: 70 },
    weeks: [
      { actual: "49%", projection: "70%" },
      { actual: "63%", projection: "70%" },
      { actual: "70%", projection: "70%" },
      { actual: "70%", projection: "70%" },
    ],
    monthlyActual: "70%",
    monthlyTarget: "",
    status: "yellow",
    owner: "AJ",
    source: "Booking Sheet",
    description: "",
  },
  {
    name: "Triage Qualification Rate",
    department: "Sales",
    catchUp: { actual: 55, projection: "50%" },
    weeks: [
      { actual: "51%", projection: "50%" },
      { actual: "49%", projection: "50%" },
      { actual: "50%", projection: "50%" },
      { actual: "50%", projection: "50%" },
    ],
    monthlyActual: "50%",
    monthlyTarget: "",
    status: "green",
    owner: "AJ",
    source: "Booking Sheet",
    description: "",
  },
  {
    name: "Closing Calls Booked",
    department: "Sales",
    catchUp: { actual: 24, projection: 238 },
    weeks: [
      { actual: 187, projection: 238 },
      { actual: 266, projection: 238 },
      { actual: 238, projection: 238 },
      { actual: 238, projection: 238 },
    ],
    monthlyActual: "",
    monthlyTarget: 1188,
    status: "yellow",
    owner: "AJ",
    source: "Booking Sheet",
    description: "",
  },
  {
    name: "Closing Call Show Rate",
    department: "Sales",
    catchUp: { actual: "79%", projection: "80%" },
    weeks: [
      { actual: "67%", projection: "80%" },
      { actual: "61%", projection: "80%" },
      { actual: "80%", projection: "80%" },
      { actual: "80%", projection: "80%" },
    ],
    monthlyActual: "80%",
    monthlyTarget: "",
    status: "yellow",
    owner: "AJ",
    source: "Booking Sheet",
    description: "",
  },
  {
    name: "Closing Calls Taken",
    department: "Sales",
    catchUp: { actual: 19, projection: 190 },
    weeks: [
      { actual: 126, projection: 190 },
      { actual: 163, projection: 190 },
      { actual: 190, projection: 190 },
      { actual: 190, projection: 190 },
    ],
    monthlyActual: "",
    monthlyTarget: 950,
    status: "yellow",
    owner: "AJ",
    source: "Booking Sheet",
    description: "",
  },
  {
    name: "Closing Call Close Rate",
    department: "Sales",
    catchUp: { actual: "21%", projection: "30%" },
    weeks: [
      { actual: "8%", projection: "30%" },
      { actual: "9%", projection: "30%" },
      { actual: "30%", projection: "30%" },
      { actual: "36%", projection: "36%" },
    ],
    monthlyActual: "30%",
    monthlyTarget: "",
    status: "red",
    owner: "AJ",
    source: "Booking Sheet",
    description: "",
  },
  // COMMUNITY MANAGEMENT
  {
    name: "Customer support complaints",
    department: "Product",
    catchUp: { actual: 0, projection: 3 },
    weeks: [
      { actual: 1, projection: 3 },
      { actual: 0, projection: 3 },
      { actual: 0, projection: 3 },
      { actual: 0, projection: 3 },
    ],
    monthlyActual: 1,
    monthlyTarget: 15,
    status: "green",
    owner: "Nicholay Voyvik",
    source: "Intercom",
    description: "The total count of complaints received from customers about products",
  },
  {
    name: "NPS Score - 2 months",
    department: "Product",
    catchUp: { actual: 10, projection: 15 },
    weeks: [
      { actual: 10, projection: 15 },
      { actual: 10, projection: 15 },
      { actual: 10, projection: 15 },
      { actual: 11, projection: 15 },
    ],
    monthlyActual: 11,
    monthlyTarget: 15,
    status: "yellow",
    owner: "Nicholay Voyvik",
    source: "Sheet",
    description: "The Net Promoter Score (NPS) is a metric used to measure customer loyalty and satisfaction",
  },
  {
    name: "NPS Score - 6 Months",
    department: "Product",
    catchUp: { actual: 8, projection: 10 },
    weeks: [
      { actual: 8, projection: 10 },
      { actual: 10, projection: 10 },
      { actual: 10, projection: 10 },
      { actual: 12, projection: 10 },
    ],
    monthlyActual: 12,
    monthlyTarget: 10,
    status: "yellow",
    owner: "Nicholay Voyvik",
    source: "Sheet",
    description: "The Net Promoter Score (NPS) based on 6-month customer data",
  },
];

export const departments: Department[] = [
  "Finance",
  "Content",
  "Marketing",
  "Sales",
  "Product",
];
